// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"
	model "movie-service/model"

	mock "github.com/stretchr/testify/mock"
)

// MockMovieService is an autogenerated mock type for the MovieService type
type MockMovieService struct {
	mock.Mock
}

type MockMovieService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMovieService) EXPECT() *MockMovieService_Expecter {
	return &MockMovieService_Expecter{mock: &_m.Mock}
}

// FetchMovies provides a mock function with given fields: ctx
func (_m *MockMovieService) FetchMovies(ctx context.Context) ([]model.Movie, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMovies")
	}

	var r0 []model.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Movie, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Movie); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieService_FetchMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMovies'
type MockMovieService_FetchMovies_Call struct {
	*mock.Call
}

// FetchMovies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMovieService_Expecter) FetchMovies(ctx interface{}) *MockMovieService_FetchMovies_Call {
	return &MockMovieService_FetchMovies_Call{Call: _e.mock.On("FetchMovies", ctx)}
}

func (_c *MockMovieService_FetchMovies_Call) Run(run func(ctx context.Context)) *MockMovieService_FetchMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMovieService_FetchMovies_Call) Return(_a0 []model.Movie, _a1 error) *MockMovieService_FetchMovies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieService_FetchMovies_Call) RunAndReturn(run func(context.Context) ([]model.Movie, error)) *MockMovieService_FetchMovies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMovieService creates a new instance of MockMovieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMovieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMovieService {
	mock := &MockMovieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
