// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	model "movie-service/model"

	mock "github.com/stretchr/testify/mock"
)

// MovieService is an autogenerated mock type for the MovieService type
type MovieService struct {
	mock.Mock
}

type MovieService_Expecter struct {
	mock *mock.Mock
}

func (_m *MovieService) EXPECT() *MovieService_Expecter {
	return &MovieService_Expecter{mock: &_m.Mock}
}

// FetchMovies provides a mock function with given fields: ctx
func (_m *MovieService) FetchMovies(ctx context.Context) ([]model.Movie, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMovies")
	}

	var r0 []model.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Movie, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Movie); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MovieService_FetchMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMovies'
type MovieService_FetchMovies_Call struct {
	*mock.Call
}

// FetchMovies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MovieService_Expecter) FetchMovies(ctx interface{}) *MovieService_FetchMovies_Call {
	return &MovieService_FetchMovies_Call{Call: _e.mock.On("FetchMovies", ctx)}
}

func (_c *MovieService_FetchMovies_Call) Run(run func(ctx context.Context)) *MovieService_FetchMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MovieService_FetchMovies_Call) Return(_a0 []model.Movie, _a1 error) *MovieService_FetchMovies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MovieService_FetchMovies_Call) RunAndReturn(run func(context.Context) ([]model.Movie, error)) *MovieService_FetchMovies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMovieService creates a new instance of MovieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieService {
	mock := &MovieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
